- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check whether products loaded 
  ansible.builtin.command: mongosh --host mongodb.buymebot.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output 
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products if not loaded
  ansible.builtin.shell: mongosh --host mongodb.buymebot.shop </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd_setup