- name: settingup a systemd service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/catalogue.service

- name: deamon-reload 
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "enable & start the {{ component }}"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes